// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.starwars.app.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface ChronologyCssResource extends CssResource {

	  @ClassName("date")
	  String date();
	  
	  @ClassName("first-date")
	  String firstDate();
	  
	  @ClassName("period-wrapper")
	  String periodWrapper();
	  
	  @ClassName("period")
	  String period();
	  
	  @ClassName("yellow-period")
	  String yellowPeriod();
	  
	  @ClassName("yellow-period-header")
	  String yellowPeriodHeader();
	  
	  @ClassName("blue-period")
	  String bluePeriod();
	  
	  @ClassName("blue-period-header")
	  String bluePeriodHeader();
	  
	  @ClassName("orange-period")
	  String orangePeriod();
	  
	  @ClassName("orange-period-header")
	  String orangePeriodHeader();
	  
	  @ClassName("violet-period")
	  String purplePeriod();
	  
	  @ClassName("violet-period-header")
	  String purplePeriodHeader();
	  
	  @ClassName("green-period")
	  String greenPeriod();
	  
	  @ClassName("green-period-header")
	  String greenPeriodHeader();
	  
	  @ClassName("events3")
	  String event3();
	  
	  @ClassName("interval")
	  String interval();
	  
	  @ClassName("interval-wrapper")
	  String intervalWrapper();
		
	  @ClassName("first")
	  String first();
	  
	  @ClassName("timeline")
	  String timeline();
	  
	  @ClassName("interval-spire")
	  String intervalSpire();
	  
	  @ClassName("event-text")
	  String eventText();
	  
	  @ClassName("event-line")
	  String eventLine();
	  
	  @ClassName("event-wrapper")
	  String eventWrapper();
}

