// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.starwars.app.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface GalaxyCssResource extends CssResource {
	  
	  @ClassName("description-background")
	  String descriptionBackground();

	  @ClassName("description-wrapper")
	  String descriptionWrapper();
	  
	  @ClassName("description-title")
	  String descriptionTitle();
	  
	  @ClassName("logo-description-wrapper")
	  String logoDescriptionWrapper();
	  
	  @ClassName("description-detail")
	  String descriptionDetail();
	  
	  @ClassName("description-mask")
	  String descriptionMask();
	  
	  @ClassName("orange-border")
	  String orangeBorder();
	  
	  @ClassName("purple-border")
	  String purpleBorder();
	  
	  @ClassName("green-border")
	  String greenBorder();
	  
	  @ClassName("blue-border")
	  String blueBorder();
	  
	  @ClassName("detail-statistics")
	  String detailStatistics();
	  
	  @ClassName("detail-statistics-line")
	  String detailStatisticsLine();

	  @ClassName("detail-stat-wrapper")
	  String detailStatWrapper();

   	  @ClassName("detail-stat-container")
	  String detailStatContainer();

	  @ClassName("detail-stat-icon")
	  String detailStatIcon();
	
	  @ClassName("detail-stat-content")
	  String detailStatContent();

	  @ClassName("detail-stat-key")
	  String detailStatKey();

	  @ClassName("detail-stat-value")
	  String detailStatValue();

	  @ClassName("detail-stat-space")
	  String detailStatSpace();

	  @ClassName("detail-stat-reference")
	  String detailStatReference();
	  
	  @ClassName("blue-font")
	  String blueFont();
	  
	  @ClassName("purple-font")
	  String purpleFont();
	  
	  @ClassName("green-font")
	  String greenFont();
	  
	  @ClassName("orange-font")
	  String orangeFont();
	  
	  @ClassName("legend-wrapper")
	  String legendWrapper();
	  
	  @ClassName("legend-text")
	  String legendText();
	  
	  @ClassName("legend-title")
	  String legendTitle();
	  
	  @ClassName("orange-legend")
	  String orangeLegend();
	  
	  @ClassName("purple-legend")
	  String purpleLegend();
	  
	  @ClassName("green-legend")
	  String greenLegend();
	  
	  @ClassName("blue-legend")
	  String blueLegend();
	  
	  @ClassName("logo-description")
	  String logoDescription();
	  
	  @ClassName("galaxy-wrapper")
	  String galaxyWrapper();
	  
	  @ClassName("galaxy")
	  String galaxy();
	  
	  @ClassName("planete")
	  String planete();
	  
	  @ClassName("planete-description")
	  String planeteDescription();
	  
	  @ClassName("title-planete-description")
	  String titlePlaneteDescription();
	  
	  @ClassName("showname-button")
	  String showButton();
	  
	  @ClassName("stars")
	  String stars();
	  
	  @ClassName("twinkling")
	  String twinkle();
	  
	  @ClassName("road")
	  String road();
	  
	  @ClassName("road-fragment")
	  String roadFragment();
	  
	  @ClassName("road-fragment-dashed")
	  String roadFragmentDashed();
	  
	  @ClassName("big")
	  String big();

	  @ClassName("territory")
	  String territory();

	  @ClassName("territory-title")
	  String territoryTitle();
	  
	  @ClassName("galaxy-chrono-main")
	  String galaxyChronoMain();
	  
	  @ClassName("galaxy-chrono-middle")
	  String galaxyChronoMiddle();

	  @ClassName("galaxy-chrono-right")
	  String galaxyChronoRight();
	  
	  @ClassName("galaxy-chrono-left")
	  String galaxyChronoLeft();
	  
	  @ClassName("galaxy-chrono-line")
	  String galaxyChronoLine();
	  
	  @ClassName("cursor")
	  String cursor();
	  
	  @ClassName("cursor-base")
	  String cursorBase();
	  
	  @ClassName("cursor-spire-top")
	  String cursorSpireTop();
	  
	  @ClassName("cursor-spire-bottom")
	  String cursorSpireBottom();
	  
	  @ClassName("period-date")
	  String periodDate();

	  @ClassName("period-date-text")
	  String periodDateText();
	  
	  @ClassName("period-date-triangle-top")
	  String periodDateTriangleTop();
	  
	  @ClassName("period-date-triangle-bottom")
	  String periodDateTriangleBottom();
	  
	  @ClassName("period-date-stick")
	  String periodDateStick();
	  
	  @ClassName("yellow-shadow-text")
	  String yellowShadowText();
	  
	  @ClassName("blue-shadow-text")
	  String blueShadowText();
	  
	  @ClassName("green-shadow-text")
	  String greenShadowText();
	  
	  @ClassName("red-shadow-text")
	  String redShadowText();
	  
	  @ClassName("orange-shadow-text")
	  String orangeShadowText();
	  
	  @ClassName("purple-shadow-text")
	  String purpleShadowText();

	  @ClassName("galaxy-text-wrapper")
	  String galaxyTextWrapper();
	  
	  @ClassName("galaxy-text-date")
	  String galaxyTextDate();
	  
	  @ClassName("galaxy-text-title")
	  String galaxyTextTitle();
	  
	  @ClassName("galaxy-text-text")
	  String galaxyTextText();
	  
	  @ClassName("yellow-spot")
	  String yellowSpot();
	  
	  @ClassName("orange-spot")
	  String orangeSpot();
}	  

