// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.starwars.app.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface GenealogyCssResource extends CssResource {
	  
	  @ClassName("blue-period")
	  String bluePeriod();
	  
	  @ClassName("blue-period-header")
	  String bluePeriodHeader();
	  
	  @ClassName("orange-period")
	  String orangePeriod();
	  
	  @ClassName("orange-period-header")
	  String orangePeriodHeader();
	  
	  @ClassName("violet-period")
	  String purplePeriod();
	  
	  @ClassName("violet-period-header")
	  String purplePeriodHeader();
	  
	  @ClassName("green-period")
	  String greenPeriod();
	  
	  @ClassName("green-period-header")
	  String greenPeriodHeader();
	  
	  @ClassName("vertical-line")
	  String verticaleLine();

	  @ClassName("horizontal-line")
	  String horizontaleLine();
	  
	  @ClassName("vertical-line-dashed")
	  String verticaleLineDashed();

	  @ClassName("horizontal-line-dashed")
	  String horizontaleLineDashed();
	  
	  @ClassName("node")
	  String node();

	  @ClassName("blue-node")
	  String blueNode();
	  
	  @ClassName("purple-node")
	  String purpleNode();
	  
	  @ClassName("orange-node")
	  String orangeNode();
	  
	  @ClassName("green-node")
	  String greenNode();
	  
	  @ClassName("red-node")
	  String redNode();
	  
	  @ClassName("darkyellow-node")
	  String darkyellowNode();
	  
	  @ClassName("mediumgreen-node")
	  String mediumgreenNode();
	  
	  @ClassName("mediumgreen2-node")
	  String mediumgreen2Node();
	  
	  @ClassName("yellow-node")
	  String yellowNode();
	  
	  @ClassName("pink-node")
	  String pinkNode();
	  
	  @ClassName("flesh-node")
	  String fleshNode();
	  
	  @ClassName("mediumpurple-node")
	  String mediumpurpleNode();
	  
	  @ClassName("darkblue-node")
	  String darkblueNode();
	  
	  @ClassName("kaki-node")
	  String kakiNode();

	  @ClassName("mediumorange-node")
	  String mediumorangeNode();
	  
	  @ClassName("node-header")
	  String nodeHeader();
	  
	  @ClassName("blue-node-header")
	  String blueNodeHeader();
	  
	  @ClassName("orange-node-header")
	  String orangeNodeHeader();
	  
	  @ClassName("purple-node-header")
	  String purpleNodeHeader();
	  
	  @ClassName("green-node-header")
	  String greenNodeHeader();
	  
	  @ClassName("red-node-header")
	  String redNodeHeader();
	  
	  @ClassName("darkyellow-node-header")
	  String darkyellowNodeHeader();
	  
	  @ClassName("mediumgreen-node-header")
	  String mediumgreenNodeHeader();
	  
	  @ClassName("mediumgreen2-node-header")
	  String mediumgreen2NodeHeader();
	  
	  @ClassName("yellow-node-header")
	  String yellowNodeHeader();
	  
	  @ClassName("mediumpurple-node-header")
	  String mediumpurpleNodeHeader();
	  
	  @ClassName("darkblue-node-header")
	  String darkblueNodeHeader();
	  
	  @ClassName("kaki-node-header")
	  String kakiNodeHeader();
	  
	  @ClassName("flesh-node-header")
	  String fleshNodeHeader();
	  
	  @ClassName("pink-node-header")
	  String pinkNodeHeader();
	  
	  @ClassName("mediumorange-node-header")
	  String mediumorangeNodeHeader();
	  
	  @ClassName("item")
	  String item();
}