// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.starwars.app.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface PagerCssResource extends CssResource {
  
  String active();
  
  @ClassName("background-progress-bar")
  String backgroundProgressBar();
  
  @ClassName("button-panel")
  String buttonPanel();
  
  @ClassName("button-panel-icon")
  String buttonPanelIcon();
  
  String column();
  
  @ClassName("column-left")
  String columnLeft();
  
  @ClassName("container-pager-item")
  String containerPagerItem();
  
  String content();
  
//  @ClassName("content-item-pedagogic-text")
//  String contentItemPedagogicText();
  
  @ClassName("detail-column")
  String detailColumn();
  
  @ClassName("detail-description")
  String detailDescription();
  
  @ClassName("detail-icon")
  String detailIcon();
  
  @ClassName("detail-icon-wrapper")
  String detailIconWrapper();
  
  @ClassName("detail-stat-container")
  String detailStatContainer();
  
  @ClassName("detail-stat-content")
  String detailStatContent();
  
  @ClassName("detail-stat-icon")
  String detailStatIcon();
  
  @ClassName("detail-stat-key")
  String detailStatKey();
  
  @ClassName("detail-stat-reference")
  String detailStatReference();
  
  @ClassName("detail-stat-space")
  String detailStatSpace();
  
  @ClassName("detail-stat-value")
  String detailStatValue();
  
  @ClassName("detail-stat-wrapper")
  String detailStatWrapper();
  
  @ClassName("detail-statistics")
  String detailStatistics();
  
  @ClassName("detail-statistics-line")
  String detailStatisticsLine();
  
  @ClassName("detail-title")
  String detailTitle();
  
  @ClassName("detail-title-content")
  String detailTitleContent();
  
  @ClassName("detail-title-line")
  String detailTitleLine();
  
  @ClassName("foreground-progress-bar")
  String foregroundProgressBar();
  
  String full();
  
  String header();
  
  @ClassName("header-pager-item")
  String headerPagerItem();
  
  @ClassName("home-blue-content")
  String homeBlueContent();
  
  @ClassName("home-intro")
  String homeIntro();
  
  @ClassName("home-logo")
  String homeLogo();
  
  @ClassName("home-white-content")
  String homeWhiteContent();
  
  @ClassName("icon-pager-item")
  String iconPagerItem();
  
//  @ClassName("item-pedagogic")
//  String itemPedagogic();
  
  String last();
  
  @ClassName("loading-background")
  String loadingBackground();
  
  @ClassName("loading-content")
  String loadingContent();
  
  @ClassName("loading-icon")
  String loadingIcon();
  
  @ClassName("loading-logo")
  String loadingLogo();
  
  @ClassName("loading-page")
  String loadingPage();
  
  @ClassName("loading-progressbar-content")
  String loadingProgressbarContent();
  
  @ClassName("loading-progressbar-shadow")
  String loadingProgressbarShadow();
  
  @ClassName("loading-progressbar-wrapper")
  String loadingProgressbarWrapper();
  
  @ClassName("loading-text")
  String loadingText();
  
  String locked();
  
  String locker();
  
  String main();
  
  String nodepath();
  
  @ClassName("nodepath-item")
  String nodepathItem();
  
  @ClassName("nodepath-item-content")
  String nodepathItemContent();
  
  @ClassName("nodepath-item-icon")
  String nodepathItemIcon();
  
  @ClassName("nodepath-separator")
  String nodepathSeparator();
  
  @ClassName("pager-main")
  String pagerMain();
  
  @ClassName("paper-column")
  String paperColumn();
  
  String pedagogic();
  
  @ClassName("progress-bar-pager-item")
  String progressBarPagerItem();
  
  String reduce();
  
  String root();
  
  @ClassName("score-background")
  String scoreBackground();
  
  @ClassName("score-button")
  String scoreButton();
  
  @ClassName("score-button-1")
  String scoreButton1();
  
  @ClassName("score-button-2")
  String scoreButton2();
  
  @ClassName("score-content")
  String scoreContent();
  
  @ClassName("score-content-ref")
  String scoreContentRef();
  
  @ClassName("score-content-value")
  String scoreContentValue();
  
  @ClassName("score-detail")
  String scoreDetail();
  
  @ClassName("score-mask")
  String scoreMask();
  
  @ClassName("score-statistics")
  String scoreStatistics();
  
  @ClassName("score-statistics-desc")
  String scoreStatisticsDesc();
  
  @ClassName("score-statistics-icon")
  String scoreStatisticsIcon();
  
  @ClassName("score-statistics-item")
  String scoreStatisticsItem();
  
  @ClassName("score-statistics-left")
  String scoreStatisticsLeft();
  
  @ClassName("score-statistics-ref")
  String scoreStatisticsRef();
  
  @ClassName("score-statistics-right")
  String scoreStatisticsRight();
  
  @ClassName("score-statistics-value")
  String scoreStatisticsValue();
  
  @ClassName("score-text")
  String scoreText();
  
  @ClassName("score-text-score")
  String scoreTextScore();
  
  @ClassName("score-text-your")
  String scoreTextYour();
  
  @ClassName("score-topright")
  String scoreTopright();
  
  @ClassName("score-topright-tag")
  String scoreToprightTag();
  
  @ClassName("score-topright-title")
  String scoreToprightTitle();
  
  @ClassName("score-wrapper")
  String scoreWrapper();
  
  String section();
  
  String semi();
  
  String separator();
  
  @ClassName("separator-pager")
  String separatorPager();
  
  String status();
  
  @ClassName("status-img")
  String statusImg();
  
  @ClassName("status-menu")
  String statusMenu();
  
  @ClassName("status-menu-list")
  String statusMenuList();
  
  @ClassName("status-menu-list-item")
  String statusMenuListItem();
  
  @ClassName("status-menu-list-separator")
  String statusMenuListSeparator();
  
  @ClassName("status-menu-wrapper")
  String statusMenuWrapper();
  
  @ClassName("status-menu-wrapper-content")
  String statusMenuWrapperContent();
  
  @ClassName("status-menu-wrapper-icon")
  String statusMenuWrapperIcon();
  
  String tag();
  
  @ClassName("timeline-container")
  String timelineContainer();
  
  @ClassName("timeline-content")
  String timelineContent();
  
  @ClassName("timeline-icon-content")
  String timelineIconContent();
  
  @ClassName("timeline-icon-full")
  String timelineIconFull();
  
  @ClassName("timeline-icon-semi")
  String timelineIconSemi();
  
  @ClassName("timeline-separator")
  String timelineSeparator();
  
  @ClassName("timeline-track")
  String timelineTrack();
  
  @ClassName("timeline-wrapper")
  String timelineWrapper();
  
  @ClassName("title-pager-item")
  String titlePagerItem();
  
  String unlocked();
  
  @ClassName("webfont-pager-item")
  String webfontPagerItem();
  
  @ClassName("wrapper-pager-item")
  String wrapperPagerItem();
  
  @ClassName("wrapper-progress-bar")
  String wrapperProgressBar();
}