// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.starwars.app.client.resources;
import com.google.gwt.resources.client.CssResource;
public interface StyleSheetCssResource extends CssResource {
  
  String absolute();
  
  String actif();
  
  String active();
  
  @ClassName("add-statement")
  String addStatement();
  
  @ClassName("add-statement-wrapper")
  String addStatementWrapper();
  
  @ClassName("apply-slider")
  String applySlider();
  
  String arrow();
  
  @ClassName("arrow-slider")
  String arrowSlider();
  
  @ClassName("arrow-slider-left")
  String arrowSliderLeft();
  
  @ClassName("arrow-slider-right")
  String arrowSliderRight();
  
  String autocompletion();
  
  @ClassName("autocompletion-hint")
  String autocompletionHint();
  
  @ClassName("autocompletion-icon")
  String autocompletionIcon();
  
  @ClassName("autocompletion-line")
  String autocompletionLine();
  
  @ClassName("autocompletion-line-diagnostic")
  String autocompletionLineDiagnostic();
  
  @ClassName("autocompletion-line-shadow")
  String autocompletionLineShadow();
  
  @ClassName("autocompletion-line-wrapper")
  String autocompletionLineWrapper();
  
  @ClassName("autocompletion-symbol")
  String autocompletionSymbol();
  
  @ClassName("autocompletion-symbol-wrapper")
  String autocompletionSymbolWrapper();
  
  String bg();
  
  @ClassName("bg-00ACE7")
  String bg00ACE7();
  
  @ClassName("bg-00ACE7-op04")
  String bg00ACE7Op04();
  
  @ClassName("bg-00ACE7-op05")
  String bg00ACE7Op05();
  
  @ClassName("bg-00ACE7-op07")
  String bg00ACE7Op07();
  
  @ClassName("bg-00ACE7-op15")
  String bg00ACE7Op15();
  
  @ClassName("bg-00ACE7-op25")
  String bg00ACE7Op25();
  
  @ClassName("bg-00ACE7-op30")
  String bg00ACE7Op30();
  
  @ClassName("bg-00ACE7-op50")
  String bg00ACE7Op50();
  
  @ClassName("bg-00ACE7-op60")
  String bg00ACE7Op60();
  
  @ClassName("bg-00ACE7-op75")
  String bg00ACE7Op75();
  
  @ClassName("bg-00ACE7-op80")
  String bg00ACE7Op80();
  
  @ClassName("bg-00ACE7-op90")
  String bg00ACE7Op90();
  
  @ClassName("bg-0D86C9")
  String bg0D86C9();
  
  @ClassName("bg-14283D")
  String bg14283D();
  
  @ClassName("bg-1C88AF")
  String bg1C88AF();
  
  @ClassName("bg-222222")
  String bg222222();
  
  @ClassName("bg-333333")
  String bg333333();
  
  @ClassName("bg-39B54A")
  String bg39B54A();
  
  @ClassName("bg-39B54A-op05")
  String bg39B54AOp05();
  
  @ClassName("bg-4D4D4D")
  String bg4D4D4D();
  
  @ClassName("bg-999999")
  String bg999999();
  
  @ClassName("bg-999999-op07")
  String bg999999Op07();
  
  @ClassName("bg-blue")
  String bgBlue();
  
  @ClassName("bg-blueLight")
  String bgBlueLight();
  
  @ClassName("bg-CCCCCC")
  String bgCCCCCC();
  
  @ClassName("bg-clip")
  String bgClip();
  
  @ClassName("bg-EA7500")
  String bgEA7500();
  
  @ClassName("bg-EA7500-op05")
  String bgEA7500Op05();
  
  @ClassName("bg-ED1C24-op05")
  String bgED1C24Op05();
  
  @ClassName("bg-F2F2F2")
  String bgF2F2F2();
  
  @ClassName("bg-F8F8F8")
  String bgF8F8F8();
  
  @ClassName("bg-FFFFFF")
  String bgFFFFFF();
  
  @ClassName("bg-FFFFFF-op05")
  String bgFFFFFFOp05();
  
  @ClassName("bg-FFFFFF-op10")
  String bgFFFFFFOp10();
  
  @ClassName("bg-transparent")
  String bgTransparent();
  
  @ClassName("bg-white")
  String bgWhite();
  
  @ClassName("bg-yellow")
  String bgYellow();
  
  @ClassName("bg-white08")
  String bgWhite08();
  
  @ClassName("bg-white-degrad")
  String bgWhiteDegrad();
  
  String bgg();
  
  String blue();
  
  @ClassName("bor-00ACE7")
  String bor00ACE7();
  
  @ClassName("bor-00ACE7-bot")
  String bor00ACE7Bot();
  
  @ClassName("bor-00ACE7-op50")
  String bor00ACE7Op50();
  
  @ClassName("bor-39B54A")
  String bor39B54A();
  
  @ClassName("bor-666666")
  String bor666666();
  
  @ClassName("bor-999999")
  String bor999999();
  
  @ClassName("bor-999999-left")
  String bor999999Left();
  
  @ClassName("bor-CCCCCC-top")
  String borCCCCCCTop();
  
  @ClassName("bor-EA7500")
  String borEA7500();
  
  @ClassName("bor-ED1C24")
  String borED1C24();
  
  @ClassName("bor-FFFFFF")
  String borFFFFFF();
  
  @ClassName("borcol-00ACE7-op25")
  String borcol00ACE7Op25();
  
  @ClassName("borcol-204957")
  String borcol204957();
  
  String bottom();
  
  @ClassName("box-absolute-wrapper")
  String boxAbsoluteWrapper();
  
  @ClassName("bt-action")
  String btAction();
  
  @ClassName("bt-open")
  String btOpen();
  
  @ClassName("bt-start")
  String btStart();
  
  @ClassName("bullet-slider")
  String bulletSlider();
  
  @ClassName("bullet-slider-wrapper")
  String bulletSliderWrapper();
  
  @ClassName("c-000000")
  String c000000();
  
  @ClassName("c-00ACE7")
  String c00ACE7();
  
  @ClassName("c-00ACE7-op50")
  String c00ACE7Op50();
  
  @ClassName("c-0D86C9")
  String c0D86C9();
  
  @ClassName("c-0FD20F")
  String c0FD20F();
  
  @ClassName("c-14283D-op40")
  String c14283DOp40();
  
  @ClassName("c-14283D-op70")
  String c14283DOp70();
  
  @ClassName("c-1C88AF")
  String c1C88AF();
  
  @ClassName("c-333333")
  String c333333();
  
  @ClassName("c-39B54A")
  String c39B54A();
  
  @ClassName("c-666666")
  String c666666();
  
  @ClassName("c-777c7e")
  String c777c7e();
  
  @ClassName("c-999999")
  String c999999();
  
  @ClassName("c-B3B3B3")
  String cB3B3B3();
  
  @ClassName("c-CCCCCC")
  String cCCCCCC();
  
  @ClassName("c-E6E6E6")
  String cE6E6E6();
  
  @ClassName("c-EA7500")
  String cEA7500();
  
  @ClassName("c-ED1C24")
  String cED1C24();
  
  @ClassName("c-EDEDED")
  String cEDEDED();
  
  @ClassName("c-F7931E")
  String cF7931E();
  
  @ClassName("c-FFFFFF")
  String cFFFFFF();
  
  String chevron();
  
  String clear();
  
  String close();
  
  @ClassName("close-panel-side")
  String closePanelSide();
  
  @ClassName("close-panel-top")
  String closePanelTop();
  
  @ClassName("close-slider")
  String closeSlider();
  
  String col();
  
  @ClassName("content-slider")
  String contentSlider();
  
  @ClassName("dis-block")
  String disBlock();
  
  @ClassName("dis-inl")
  String disInl();
  
  @ClassName("dis-none")
  String disNone();
  
  @ClassName("dock-question-down")
  String dockQuestionDown();
  
  @ClassName("dock-question-up")
  String dockQuestionUp();

  String drag();
  
  String droidsans();
  
  @ClassName("droidsans-bold")
  String droidsansBold();
  
  String drop();
  
  String edit();
  
  @ClassName("error-one")
  String errorOne();
  
  @ClassName("error-two")
  String errorTwo();
  
  @ClassName("exercice-content")
  String exerciceContent();
  
  @ClassName("exercice-editbar")
  String exerciceEditbar();
  
  @ClassName("exercice-editbar-button")
  String exerciceEditbarButton();
  
  @ClassName("exercice-header")
  String exerciceHeader();
  
  @ClassName("exercice-mask")
  String exerciceMask();
  
  @ClassName("exercice-wrapper")
  String exerciceWrapper();
  
  @ClassName("exercise-black-theme")
  String exerciseBlackTheme();
  
  @ClassName("exercise-button")
  String exerciseButton();
  
  @ClassName("exercise-nav")
  String exerciseNav();
  
  @ClassName("f-11")
  String f11();
  
  @ClassName("f-12")
  String f12();
  
  @ClassName("f-13")
  String f13();
  
  @ClassName("f-14")
  String f14();
  
  @ClassName("f-15")
  String f15();
  
  @ClassName("f-16")
  String f16();
  
  @ClassName("f-17")
  String f17();
  
  @ClassName("f-18")
  String f18();
  
  @ClassName("f-20")
  String f20();
  
  @ClassName("f-22")
  String f22();
  
  @ClassName("f-23")
  String f23();
  
  @ClassName("f-24")
  String f24();
  
  @ClassName("f-27")
  String f27();
  
  @ClassName("f-30")
  String f30();
  
  @ClassName("f-32")
  String f32();
  
  @ClassName("f-35")
  String f35();
  
  @ClassName("f-40")
  String f40();
  
  @ClassName("f-46")
  String f46();
  
  @ClassName("f-70")
  String f70();
  
  @ClassName("f-bold")
  String fBold();
  
  @ClassName("f-center")
  String fCenter();
  
  @ClassName("f-jus")
  String fJus();
  
  @ClassName("f-right")
  String fRight();
  
  @ClassName("f-und")
  String fUnd();
  
  @ClassName("f-upp")
  String fUpp();
  
  String f_circleG();
  
  String fixed();
  
  @ClassName("geometricslabserif-bold")
  String geometricslabserifBold();
  
  @ClassName("geometricslabserif-medium")
  String geometricslabserifMedium();
  
  @ClassName("geometricslabserif-medium-italic")
  String geometricslabserifMediumItalic();
  
  @ClassName("grad-blue")
  String gradBlue();
  
  @ClassName("grad-blue-line")
  String gradBlueLine();
  
  @ClassName("grad-bronze")
  String gradBronze();
  
  @ClassName("grad-dark")
  String gradDark();
  
  @ClassName("grad-dark-line")
  String gradDarkLine();
  
  @ClassName("grad-gold")
  String gradGold();
  
  @ClassName("grad-reflect")
  String gradReflect();
  
  @ClassName("grad-silver")
  String gradSilver();
  
  String green();
  
  String grey();
  
  @ClassName("h-40")
  String h40();
  
  @ClassName("hack-safari")
  String hackSafari();
  
  @ClassName("hint-wrapper")
  String hintWrapper();
  
  @ClassName("hint-wrapper-hidden")
  String hintWrapperHidden();
  
  String icon();
  
  @ClassName("icon-10px")
  String icon10px();
  
  @ClassName("icon-128px")
  String icon128px();
  
  @ClassName("icon-16px")
  String icon16px();
  
  @ClassName("icon-20px")
  String icon20px();
  
  @ClassName("icon-25px")
  String icon25px();
  
  @ClassName("icon-32px")
  String icon32px();
  
  @ClassName("icon-35px")
  String icon35px();
  
  @ClassName("icon-64px")
  String icon64px();
  
  @ClassName("icon-statement")
  String iconStatement();
  
  String inactif();
  
  String inactive();
  
  String item();
  
  @ClassName("item-lock")
  String itemLock();
  
  @ClassName("item-nav")
  String itemNav();
  
  @ClassName("item-wrapper")
  String itemWrapper();
  
  @ClassName("l-104per")
  String l104per();
  
  @ClassName("l-108per")
  String l108per();
  
  @ClassName("lb-loading")
  String lbLoading();
  
  @ClassName("lb-mask")
  String lbMask();
  
  @ClassName("lb-wrapper")
  String lbWrapper();
  
  String left();
  
  @ClassName("lh-130per")
  String lh130per();
  
  String line();
  
  String loadingBar();
  
  String loadingLogo();
  
  String lock();
  
  String logo();
  
  @ClassName("m-auto")
  String mAuto();
  
  @ClassName("m-b10")
  String mB10();
  
  @ClassName("m-b5")
  String mB5();
  
  @ClassName("m-l10")
  String mL10();
  
  @ClassName("m-l20")
  String mL20();
  
  @ClassName("m-l5")
  String mL5();
  
  @ClassName("m-r10")
  String mR10();
  
  @ClassName("m-r15")
  String mR15();
  
  @ClassName("m-r5")
  String mR5();
  
  @ClassName("m-r5-neg")
  String mR5Neg();
  
  @ClassName("m-t10")
  String mT10();
  
  @ClassName("m-t12")
  String mT12();
  
  @ClassName("m-t14")
  String mT14();
  
  @ClassName("m-t2")
  String mT2();
  
  @ClassName("m-t48")
  String mT48();
  
  @ClassName("m-t25-neg")
  String mT25Neg();
  
  @ClassName("m-t27-neg")
  String mT27Neg();
  
  @ClassName("m-t3")
  String mT3();
  
  @ClassName("m-t30")
  String mT30();
  
  @ClassName("m-t5")
  String mT5();
  
  @ClassName("m-t5-neg")
  String mT5Neg();
  
  @ClassName("m-t7")
  String mT7();
  
  @ClassName("m-t8")
  String mT8();
  
  @ClassName("m-t96")
  String mT96();
  
  @ClassName("m-y10")
  String mY10();
  
  @ClassName("m-y15")
  String mY15();
  
  @ClassName("menu-drop-content")
  String menuDropContent();
  
  @ClassName("menu-drop-wrapper")
  String menuDropWrapper();
  
  String middle();
  
  @ClassName("nav-current")
  String navCurrent();
  
  @ClassName("nav-home")
  String navHome();
  
  @ClassName("nav-next")
  String navNext();
  
  String number();
  
  @ClassName("number-slider")
  String numberSlider();
  
  @ClassName("number-statement")
  String numberStatement();
  
  @ClassName("number-wrapper")
  String numberWrapper();
  
  String onover();
  
  @ClassName("op-0")
  String op0();
  
  @ClassName("op-30")
  String op30();
  
  @ClassName("op-50")
  String op50();
  
  @ClassName("op-70")
  String op70();
  
  @ClassName("op-80")
  String op80();
  
  @ClassName("op-99")
  String op99();
  
  String opacity();
  
  String open();
  
  String orange();
  
  @ClassName("ov-hidden")
  String ovHidden();
  
  @ClassName("p-b10")
  String pB10();
  
  @ClassName("p-l10")
  String pL10();
  
  @ClassName("p-l1per")
  String pL1per();
  
  @ClassName("p-r1per")
  String pR1per();
  
  @ClassName("p-t10")
  String pT10();
  
  @ClassName("p-t2")
  String pT2();
  
  @ClassName("p-t3")
  String pT3();
  
  @ClassName("p-t4")
  String pT4();
  
  @ClassName("p-t40")
  String pT40();
  
  @ClassName("p-t5")
  String pT5();
  
  @ClassName("p-t8")
  String pT8();
  
  @ClassName("p-x10")
  String pX10();
  
  @ClassName("p-x15")
  String pX15();
  
  @ClassName("p-x20")
  String pX20();
  
  @ClassName("p-x5")
  String pX5();
  
  @ClassName("p-x7")
  String pX7();
  
  @ClassName("p-y10")
  String pY10();
  
  @ClassName("p-y14")
  String pY14();
  
  @ClassName("p-y2")
  String pY2();
  
  @ClassName("p-y20")
  String pY20();
  
  @ClassName("p-y5")
  String pY5();
  
  @ClassName("p-y6")
  String pY6();
  
  @ClassName("p-y7")
  String pY7();
  
  String panel();
  
  @ClassName("panel-back")
  String panelBack();
  
  @ClassName("panel-top-paragraph")
  String panelTopParagraph();
  
  @ClassName("panel-top-title")
  String panelTopTitle();
  
  @ClassName("pastille-speciale")
  String pastilleSpeciale();
  
  String pointer();
  
  @ClassName("progress-bar")
  String progressBar();
  
  @ClassName("progressBar")
  String progressBar_();
  
  @ClassName("qcm-blue")
  String qcmBlue();
  
  @ClassName("qcm-green")
  String qcmGreen();
  
  @ClassName("qcm-initial")
  String qcmInitial();
  
  @ClassName("qcm-red")
  String qcmRed();
  
  @ClassName("rad-3")
  String rad3();
  
  @ClassName("rad-5")
  String rad5();
  
  @ClassName("rad-full")
  String radFull();
  
  String relative();
  
  String right();
  
  String score();
  
  String selected();
  
  String separator();
  
  String shadow();
  
  String side();
  
  @ClassName("sp-10")
  String sp10();
  
  @ClassName("sp-15")
  String sp15();
  
  @ClassName("sp-20")
  String sp20();
  
  @ClassName("sp-25")
  String sp25();
  
  @ClassName("sp-30")
  String sp30();
  
  @ClassName("sp-40")
  String sp40();
  
  @ClassName("sp-5")
  String sp5();
  
  @ClassName("sp-80")
  String sp80();
  
  String special();
  
  String statement();
  
  @ClassName("statement-depend")
  String statementDepend();
  
  @ClassName("statement-inactive-wrapper")
  String statementInactiveWrapper();
  
  @ClassName("statement-line-separator")
  String statementLineSeparator();
  
  @ClassName("statement-special-wrapper")
  String statementSpecialWrapper();
  
  @ClassName("statement-writing")
  String statementWriting();
  
  String top();
  
  @ClassName("trans-all")
  String transAll();
  
  @ClassName("trans-appear1")
  String transAppear1();
  
  @ClassName("trans-appear4")
  String transAppear4();
  
  @ClassName("trans-appear35")
  String transAppear35();
  
  @ClassName("trans-bg")
  String transBg();
  
  @ClassName("trans-border")
  String transBorder();
  
  @ClassName("trans-color")
  String transColor();
  
  @ClassName("trans-opacity")
  String transOpacity();
  
  @ClassName("trans-width")
  String transWidth();
  
  @ClassName("trophy-nav")
  String trophyNav();
  
  @ClassName("vis-hidden")
  String visHidden();
  
  @ClassName("w-100per")
  String w100per();
  
  @ClassName("w-10per")
  String w10per();
  
  @ClassName("w-110per")
  String w110per();
  
  @ClassName("w-15per")
  String w15per();
  
  @ClassName("w-220min")
  String w220min();
  
  @ClassName("w-30")
  String w30();
  
  @ClassName("w-30per")
  String w30per();
  
  @ClassName("w-310max")
  String w310max();
  
  @ClassName("w-32per")
  String w32per();
  
  @ClassName("w-40")
  String w40();
  
  @ClassName("w-400max")
  String w400max();
  
  @ClassName("w-45per")
  String w45per();
  
  @ClassName("w-5")
  String w5();
  
  @ClassName("w-55per")
  String w55per();
  
  @ClassName("w-5per")
  String w5per();
  
  @ClassName("w-60per")
  String w60per();
  
  @ClassName("w-65")
  String w65();
  
  @ClassName("w-70per")
  String w70per();
  
  @ClassName("w-72per")
  String w72per();
  
  @ClassName("w-75per")
  String w75per();
  
  @ClassName("w-80per")
  String w80per();
  
  @ClassName("w-83per")
  String w83per();
  
  @ClassName("w-84per")
  String w84per();
  
  @ClassName("w-86per")
  String w86per();
  
  @ClassName("w-87per")
  String w87per();
  
  @ClassName("w-90per")
  String w90per();
  
  @ClassName("w-91per")
  String w91per();
  
  @ClassName("w-95per")
  String w95per();
  
  @ClassName("w-200per")
  String w200per();
  
  @ClassName("webfont-icon")
  String webfontIcon();
  
  String wrapper();
  
  @ClassName("z-1001")
  String z1001();
  
  @ClassName("z-999")
  String z999();
  
  @ClassName("toc-line")
  String tocLine();
  
  @ClassName("m-t16")
  String mT16();
  
  @ClassName("tips-drag-pic")
  String tipsDragPic();
  
  @ClassName("justify-bt")
  String justifyBt();
  
  @ClassName("quick-access")
  String quickAcces();
  
  @ClassName("bounce")
  String bounce();
  
  @ClassName("preuve")
  String preuve();
  
  @ClassName("hide")
  String hide();
  
  @ClassName("preuve-line")
  String preuveLine();
  
  @ClassName("trans-all-10")
  String transAll10();
  
  @ClassName("toc-note")
  String tocNote();
  
  @ClassName("quick-access-icon")
  String quickAcessIcon();
  
  @ClassName("toc-title")
  String tocTitle();
  
  @ClassName("unlock")
  String unlock();
  
  @ClassName("tips-title")
  String tipsTitle();
  
  @ClassName("select-top")
  String selectTop();
  
  @ClassName("justify-wp")
  String justifyWp();
  
  @ClassName("tips-drag-icon")
  String tipsDragIcon();
  
  @ClassName("semi-actif")
  String semiActif();
  
  @ClassName("header")
  String header();
  
  @ClassName("content")
  String content();
  
  @ClassName("bis")
  String bis();
  
  @ClassName("preuve-item")
  String preuveItem();
  
  @ClassName("trans-all-25")
  String transAll25();
  
  @ClassName("tips-text")
  String tipsText();
  
  @ClassName("verroux")
  String verroux();
  
  @ClassName("pastille-triangle")
  String pastilleTriangle();
  
  @ClassName("m-b20")
  String mB20();
  
  @ClassName("toc-number")
  String tocNumber();
  
  @ClassName("c-F2F2F2")
  String cf2f2f2();
  
  @ClassName("desactivate")
  String desactivate();
  
  @ClassName("toc-menu")
  String tocMenu();
  
  @ClassName("bigger")
  String bigger();
  
  @ClassName("preuve-wrapper")
  String preuveWrapper();
  
  @ClassName("docked-paper-controls")
  String dockedPaperControls();
  
  @ClassName("icon-correction")
  String iconCorrection();
  
  @ClassName("timeline")
  String timeline();
  
  @ClassName("correction")
  String correction();
  
  @ClassName("home-logo")
  String homeLogo();
  
  @ClassName("tl-trait")
  String tlTrait();
  
  @ClassName("toc-result")
  String tocResult();
  
  @ClassName("note-hidden")
  String noteHidden();
  
  @ClassName("info-box-content")
  String infoBoxContent();
  
  @ClassName("tl-rond")
  String tlRond();
  
  @ClassName("home-intro")
  String homeIntro();
  
  @ClassName("timeline-wrapper")
  String timelineWrapper();
  
  @ClassName("pastille-mask")
  String pastilleMask();
  
  @ClassName("icon-close")
  String iconClose();
  
  @ClassName("covered")
  String covered();
  
  @ClassName("info-box")
  String infoBox();
  
  @ClassName("m-t25")
  String mT25();
  
  @ClassName("preuve-line-wrapper")
  String preuveLineWrapper();
  
  @ClassName("info-box-open")
  String infoBoxOpen();
  
  @ClassName("semi-assist")
  String semiAssist();
  
  @ClassName("footer")
  String footer();
  
  @ClassName("red")
  String red();
  
  @ClassName("select-bottom")
  String selectBottom();
  
  @ClassName("pastille-instantation")
  String pastilleInstantation();
  
  @ClassName("bt-open-close")
  String btOpenClose();
  
  @ClassName("no-assist")
  String noAssist();
  
  @ClassName("tips")
  String tips();
 
  @ClassName("width-auto")
  String widthAuto();
  
  @ClassName("ovy-hidden")
  String ovyHidden();
  
  @ClassName("webkit-box")
  String webkitBox();
  
  @ClassName("table")
  String table();
  
  @ClassName("flex")
  String flex();
  
  @ClassName("list-item")
  String listItem();
  
  @ClassName("inline-table")
  String inlineTable();
  
  @ClassName("left-zero")
  String leftZero();
  
  @ClassName("zoom-50")
  String zoom50();
  
  @ClassName("zoom-60")
  String zoom60();
  
  @ClassName("zoom-65")
  String zoom65();
  
  @ClassName("zoom-70")
  String zoom70();
  
  @ClassName("zoom-80")
  String zoom80();
  
  @ClassName("zoom-85")
  String zoom85();
  
  @ClassName("zoom-88")
  String zoom88();
  
  @ClassName("zoom-89")
  String zoom89();
  
  @ClassName("zoom-90")
  String zoom90();
  
  @ClassName("zoom-100")
  String zoom100();
  
  @ClassName("zoom-1001")
  String zoom1001();
  
  @ClassName("zoom-1002")
  String zoom1002();
  
  @ClassName("zoom-1005")
  String zoom1005();
  
  @ClassName("zoom-115")
  String zoom115();
  
  @ClassName("zoom-145")
  String zoom145();
  
  @ClassName("zoom-165")
  String zoom165();
  
  @ClassName("about")
  String about();
  
  @ClassName("description-background")
  String descriptionBackground();

  @ClassName("description-wrapper")
  String descriptionWrapper();

  @ClassName("logo-description-wrapper")
  String logoDescriptionWrapper();

  @ClassName("logo-description")
  String logoDescription();

  @ClassName("description-title")
  String descriptionTitle();

  @ClassName("description-detail")
  String descriptionDetail();

  @ClassName("description-mask")
  String descriptionMask();
  
  @ClassName("blue-border")
  String blueBorder();
  
  @ClassName("description-part")
  String descriptionPart();
  
  @ClassName("research-button")
  String researchButton();
  
  @ClassName("research-wrapper")
  String researchWrapper();
  
  @ClassName("textbox")
  String textbox();
  
  @ClassName("textbox-wrapper")
  String textboxWrapper();
  
  @ClassName("fadein1")
  String fadein1();
  
  @ClassName("fadein05")
  String fadein05();
  
  @ClassName("rad-15")
  String rad15();
  
  @ClassName("shadow-box")
  String shadowBox();
  
  @ClassName("blue-shadow-box")
  String blueShadowBox();
  
  @ClassName("main-portal")
  String mainPortal();
  
  @ClassName("portal")
  String portal();
  
  @ClassName("legends-portal-image")
  String legendsPortalImage();
  
  @ClassName("classic-portal-image")
  String classicPortalImage();
  
  @ClassName("main-portal-wrapper")
  String mainPortalWrapper();
  
  @ClassName("legends-portal")
  String legendsPortal();
  
  @ClassName("classic-portal")
  String classicPortal();
  
  @ClassName("portal-title")
  String portalTitle();

  @ClassName("portal-subtitle")
  String portalSubTitle();
  
  @ClassName("portal-text")
  String portalText();

  @ClassName("portal-text-title")
  String portalTextTitle();

  @ClassName("portal-text-paragraph")
  String portalTextParagrah();
  
  @ClassName("fadeout85")
  String fadeout85();
  
  @ClassName("fadein85")
  String fadein85();
  
  @ClassName("holo-wrapper")
  String holoWrapper();
  
  @ClassName("holoprojection")
  String holoProjection();
  
  @ClassName("holoprojector-shadow")
  String holoprojectorShadow();
  
  @ClassName("background")
  String background();
  
  @ClassName("beta")
  String beta();
  
  @ClassName("circles")
  String circles();
  
  @ClassName("circle-m")
  String circleM();
  
  @ClassName("circle1")
  String circle1();
  
  @ClassName("circle2")
  String circle2();
  
  @ClassName("background-traits")
  String backgroundTraits();
  
  @ClassName("fadein3sec")
  String fadein3sec();
  
  @ClassName("origin-initial")
  String originInitial();
  
  @ClassName("origin-top")
  String originTop();
  
  @ClassName("position-initial")
  String positionInitial();
  
  @ClassName("orange-border")
  String orangeBorder();
  
  @ClassName("purple-border")
  String purpleBorder();
  
  @ClassName("green-border")
  String greenBorder();
  
  @ClassName("kaki-border")
  String kakiBorder();
  
  @ClassName("yellow-border")
  String yellowBorder();
  
  @ClassName("darkblue-border")
  String darkblueBorder();
  
  @ClassName("darkyellow-border")
  String darkyellowBorder();
  
  @ClassName("pink-border")
  String pinkBorder();
  
  @ClassName("mediumgreen-border")
  String mediumgreenBorder();
  
  @ClassName("mediumgreen2-border")
  String mediumgreen2Border();
  
  @ClassName("mediumorange-border")
  String mediumorangeBorder();
  
  @ClassName("mediumpurple-border")
  String mediumpurpleBorder();
  
  @ClassName("red-border")
  String redBorder();
  
  @ClassName("flesh-border")
  String fleshBorder();
  
  @ClassName("orange-legend")
  String orangeLegend();
  
  @ClassName("blue-legend")
  String blueLegend();
  
  @ClassName("purple-legend")
  String purpleLegend();
  
  @ClassName("green-legend")
  String greenLegend();
  
  @ClassName("kaki-legend")
  String kakiLegend();
  
  @ClassName("yellow-legend")
  String yellowLegend();
  
  @ClassName("darkblue-legend")
  String darkblueLegend();
  
  @ClassName("darkyellow-legend")
  String darkyellowLegend();
  
  @ClassName("pink-legend")
  String pinkLegend();
  
  @ClassName("mediumgreen-legend")
  String mediumgreenLegend();
  
  @ClassName("mediumgreen2-legend")
  String mediumgreen2Legend();
  
  @ClassName("mediumorange-legend")
  String mediumorangeLegend();
  
  @ClassName("mediumpurple-legend")
  String mediumpurpleLegend();
  
  @ClassName("red-legend")
  String redLegend();
  
  @ClassName("flesh-legend")
  String fleshLegend();
  
  @ClassName("detail-statistics")
  String detailStatistics();
  
  @ClassName("detail-statistics-line")
  String detailStatisticsLine();

  @ClassName("detail-stat-wrapper")
  String detailStatWrapper();

  @ClassName("detail-stat-container")
  String detailStatContainer();

  @ClassName("detail-stat-icon")
  String detailStatIcon();

  @ClassName("detail-stat-content")
  String detailStatContent();

  @ClassName("detail-stat-key")
  String detailStatKey();

  @ClassName("detail-stat-value")
  String detailStatValue();

  @ClassName("detail-stat-space")
  String detailStatSpace();

  @ClassName("detail-stat-reference")
  String detailStatReference();
  
  @ClassName("blue-font")
  String blueFont();
  
  @ClassName("white-font")
  String whiteFont();
  
  @ClassName("yellow-font")
  String yellowFont();
  
  @ClassName("kaki-font")
  String kakiFont();
  
  @ClassName("darkyellow-font")
  String darkyellowFont();
  
  @ClassName("darkblue-font")
  String darkblueFont();
  
  @ClassName("red-font")
  String redFont();
  
  @ClassName("mediumpurple-font")
  String mediumpurpleFont();
  
  @ClassName("mediumorange-font")
  String mediumorangeFont();
  
  @ClassName("mediumgreen-font")
  String mediumgreenFont();
  
  @ClassName("mediumgreen2-font")
  String mediumgreen2Font();
  
  @ClassName("pink-font")
  String pinkFont();
  
  @ClassName("flesh-font")
  String fleshFont();
  
  @ClassName("purple-font")
  String purpleFont();
  
  @ClassName("green-font")
  String greenFont();
  
  @ClassName("orange-font")
  String orangeFont();
  
  @ClassName("left-scroll")
  String leftScroll();
  
  @ClassName("right-direction")
  String rightDirection();
  
  @ClassName("doc-text")
  String docText();
  
  @ClassName("height-auto")
  String heightAuto();
  
  @ClassName("doc-image")
  String docImage();
  
  @ClassName("ov-initial")
  String ovInitial();
  
  @ClassName("origin-left-top")
  String originLeftTop();
  
  @ClassName("background-trans-blue-active")
  String backgroundTransBlueActive();
  
  @ClassName("background-trans-blue-inactive")
  String backgroundTransBlueInactive();
  
  @ClassName("border-radius-opposite5")
  String borderRadiusOpposite5();
  
  @ClassName("border-radius-opposite10")
  String borderRadiusOpposite10();
  
  @ClassName("border-radius-opposite16")
  String borderRadiusOpposite16();
  
  @ClassName("hyperlink")
  String hyperlink();
  
  @ClassName("hyperlink-description")
  String hyperlinkDescription();
  
  @ClassName("hyperlink-description-text")
  String hyperlinkDescriptionText();
	  
  @ClassName("hyperlink-description-wrapper-image")
  String hyperlinkDescriptionWrapperImage();
  
  @ClassName("hyperlink-description-image")
  String hyperlinkDescriptionImage();
  
  @ClassName("doc-title-line")
  String docTitleLine();
  
  @ClassName("portal-cadre-theme")
  String portalCadreTheme();
  
  @ClassName("reflect")
  String reflect();
  
  @ClassName("reflect85")
  String reflect85();
  
  @ClassName("legend-wrapper")
  String legendWrapper();

  @ClassName("legend-title")
  String legendTitle();

  @ClassName("legend-text")
  String legendText();

  @ClassName("band")
  String band();
  
  @ClassName("send-wrapper")
  String sendWrapper();
  
  @ClassName("text-area")
  String textArea();
  
  @ClassName("label-txt")
  String labelTxt();
  
  @ClassName("label-txt-active")
  String labelTxtActive();
  
  @ClassName("header-portal")
  String headerPortal();
  
  @ClassName("footer-portal")
  String footerPortal();
  
  @ClassName("black-shadow-text")
  String blackShadowText();
  
  @ClassName("search-area")
  String searchArea();
}
